# Generated by Django 2.2.11 on 2020-03-17 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('aname', models.CharField(max_length=100)),
                ('content', models.CharField(blank=True, max_length=10000, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('hits', models.IntegerField(blank=True, null=True)),
                ('comments', models.IntegerField(blank=True, null=True)),
                ('picture', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'article',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=50)),
                ('article_number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=128)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('head_portrait', models.CharField(blank=True, max_length=300, null=True)),
                ('register_time', models.DateTimeField(blank=True, null=True)),
                ('is_forbidden', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('tname', models.CharField(max_length=50)),
                ('aid', models.ForeignKey(blank=True, db_column='aid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='App.Article')),
            ],
            options={
                'db_table': 'tag',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comid', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(blank=True, max_length=300, null=True)),
                ('comment_time', models.DateTimeField(blank=True, null=True)),
                ('new_column', models.IntegerField(blank=True, null=True)),
                ('uid', models.ForeignKey(blank=True, db_column='uid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='App.User')),
            ],
            options={
                'db_table': 'comments',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='article',
            name='cid',
            field=models.ForeignKey(blank=True, db_column='cid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='App.Category'),
        ),
    ]
